name: Build Artifacts
on:
  push:
    branches:
      - '**'
env:
  TAG_NAME: ${{ github.event.release.tag_name || (github.ref == 'refs/heads/main' && 'main') }}
jobs:
  multiplatform_build:
    strategy:
      fail-fast: false
      matrix:
        component:
          - name: docker-opensearch
            file: docker/Dockerfile
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up JDK for Maven Build
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
      - name: Build Maven Project
        run: |
          cd opensearch-filter-plugin
          mvn clean package
      - name: Archive build output
        run: |
          mv opensearch-filter-plugin/target/opensearch-filter-plugin-2.11.1.0.zip docker/opensearch-filter-plugin-2.11.1.0.zip
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${GITHUB_ACTOR}
          password: ${{secrets.GITHUB_TOKEN}}
      - name: List files in `opensearch-filter-plugin/target`
        run: ls -l opensearch-filter-plugin/target

      - name: List files in `docker`
        run: ls -l docker
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          no-cache: true
          context: .
          file: ${{ matrix.component.file }}
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ghcr.io/netcracker/${{ matrix.component.name }}:${{ env.TAG_NAME }}
          provenance: false
